# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job-debian:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i --global yarn
    - run: yarn dist -l
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: cypher-debian
          path: |
            /home/runner/work/Cypher-System-App/Cypher-System-App/release/**/*.AppImage
  job-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i --global yarn
    - run: yarn dist -w
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: cypher-windows
          path: |
            D:\a\Cypher-System-App\Cypher-System-App\release\**\*.exe
            
